apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-service
  namespace: netology
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: nginx-port
      protocol: TCP
      port: 80
    - name: multitool-port
      protocol: TCP
      port: 8080
  type: NodePort