apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  namespace: netology
spec:
  type: NodePort
  selector:
    app: nginx-multitool
  ports:
    - port: 80
      name: nginx-port
      nodePort: 30011

