apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-service
  namespace: netology
spec:
  selector:
    app: nginx-multitool
  ports:
  - name: nginx-port
    protocol: TCP
    port: 9001
    targetPort: 80
  - name: multitool-port
    protocol: TCP
    port: 9002
    targetPort: 1180